{% set name = "et_xmlfile" %}
{% set version = "1.1.0" %}
{% set sha256 = "8eb9e2bc2f8c97e37a2dc85a09ecdcdec9d8a396530a6d5a33b30b9a92da0c5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - et_xmlfile

about:
  home: https://bitbucket.org/openpyxl/et_xmlfile
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENCE.rst
  summary: An implementation of lxml.xmlfile for the standard library

  description: |
    et_xmlfile is a low memory library for creating large XML files.
  doc_url: https://et-xmlfile.readthedocs.io
  dev_url: https://bitbucket.org/openpyxl/et_xmlfile

extra:
  recipe-maintainers:
    - curtisalexander
