travis:
  secure:
    BINSTAR_TOKEN: NDtnYm11h5+hnHVHJVrg6rX0caGPymDGvRQY+GMLIKpJl6B4MKQPqeynyajnmJ/pGQ5u9Fb5gwzR/VO0BcJpNw/Z56ofc/F9Zl5nyF232xvTQdLWVTQYw3pby+hhAmKJtZ4thf8Ace0SLZPvoxzU7xQj7hQHv+ZHW+Tks+iAFDA1shWnrhpvaB+Vu6g692mGJad80Tkn1LHjnkXOGClcJ5vEU2FAN0Jw8NS7vB+QBNmoaAqZ3yCoNXNipUL8t/y+lgSE4MnclboldcykUSkWeXXrbJlgq9QhyetwWh9ohKsan1gxlvS14HRpRJHeZgJ7JNx0hf/mSB3DI61iNFZ40kNPEOe7oBUi4Ko8n/EqS5dqmcWOcE7AX9LpSLyx6i3f5UDIE30llZCAsNiqu7vgw5hqQlvso8hW+dRMYD6ypOf+Vn6EWqXyBMEOSlb20MgESwzSD11yoPxN4CVWOTPgHIKvKBIM67E7K/RA1LZuQgMRDsU1sUlaadM4oX3WC7MfiCilancQWylnz85iNdF+wpjH7F+45WdyNV8ZUewZ/umHiL9B6tXct7jusR7ouNpeVF/e98gEwCpeIJYPvf3LBA3pKX+BkCuNbf+wnYlf9+YsAyDtmeOWcRRrbkm2W3ga8W/M2BBlVqT9cBoobiXdHV9tJy9XuU+oS2HiOy6YclY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
